### ISSUE TITLE
Bug: Admin frontend resources unable to access

### ISSUE THREAD

**Issue by keelewang** [openimsdk/open-im-server#1813] opened 2024-01-25 10:07 UTC
### What happened?

After I deployed open-im-server and chat , admin fronted page counld not opened. It is not started on my machine.

### What did you expect to happen?

http://ip:11002 can be accessed normally

### How can we reproduce it (as minimally and precisely as possible)?

https://docs.openim.io/guides/gettingStarted/mac-deployment-guide

### Anything else we need to know?

PC Web frontend resources is normal, and "make check" output "Check all openim service ports successfully"

### version

<details>
```console
$ {name} version
# paste output here
```
</details>

### Cloud provider

<details>
</details>

### OS version

<details>
Model Name: MacBook Air
Model Identifier: Mac14,2
Chip: Apple M2
Total Number of Cores: 8 (4 performance and 4 efficiency)
Memory: 16 GB

Darwin MacBook-Air.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112 arm64
</details>

### Install tools

<details>
</details>

**Comment by skiffer-git** [comment] 2024-01-26 01:32
Did you deploy using Docker, or did you use the source code directly?

**Comment by keelewang** [comment] 2024-01-26 01:35
> Did you deploy using Docker, or did you use the source code directly?

I use the source code .

**Comment by cubxxw** [comment] 2024-01-26 02:15
I hope this message finds you well. I noticed from your issue description that you are using a Mac for deploying OpenIM. In order to assist you more effectively, I have a few questions and would appreciate if you could provide some additional information. This will help us understand the root cause of the problem and guide you towards a solution.

Could you please run the following commands in your terminal and share the outputs with us? These commands will give us a clearer picture of your current Docker environment and the status of the OpenIM services:

1. `docker ps` - To list the running Docker containers.
2. `docker images` - To show the Docker images currently available on your machine.
3. `docker compose logs openim-server` - To retrieve logs from the OpenIM server container.
4. `docker compose logs openim-chat` - To obtain logs from the OpenIM chat container.

Additionally, if you could provide your `config/config.yaml` file, it would be immensely helpful. This file contains important configuration settings, and reviewing it might reveal potential misconfigurations or other issues relevant to the deployment problem.

Please ensure that any sensitive information is redacted before sharing your configuration file or logs.

Thank you for your cooperation and patience. We are committed to resolving your issue and look forward to your response.

@keelewang

**Closed** 2024-03-03 10:32 UTC
Labels: kind/bug

**Comment by keelewang** [comment] 2024-03-03 10:33
Solved with #1879
